### ISSUE TITLE
Provide user-input validation

### ISSUE THREAD

**Issue by lymereJ** [pnnl/copper#52]
As per a discussion with @jugonzal07, Copper should provide some degree of user-input validation. 

Examples:
- Do not attempt to run if the input reference capacity of a chiller is 0 or negative
- Do not attempt to run if the input targeted full load efficiency or part load efficiency of a chiller is 0 or negative

**Comment by ChristensenCode** [comment]
I added a json schema so I'll make it it's own branch and submit a pull request with that in the next week or so. 

Schemas are so nice for input validation.

**Comment by lymereJ** [comment]
Addressed in #72.
