### ISSUE TITLE
JOSS Review: Address citation format for reference in paper (Missing Author)

### ISSUE THREAD

**Issue by samuelduchesne** [pnnl/copper#58]
Can the first two references have an author (Main author or organization)? instead, the whole title is referenced as the author, which makes it hard to read.

![image](https://user-images.githubusercontent.com/22966009/205451763-dda67078-113a-4d0e-9f1d-8df90bd63dc9.png)

**Comment by lymereJ** [comment]
Hi @samuelduchesne - I believe that organization was already in. I added authors, but I still see the same outcome in the PDF. Here's the latest: https://github.com/pnnl/copper/actions/runs/3633532550. Do you know what could be the reason for that? I'll keep looking on my end as well.
