### ISSUE TITLE
Enhancement: Comprehensive Update and Bug Fixes for Unitary DX System

### ISSUE THREAD

**Issue by wanhanlong1130** [pnnl/copper#82]
### Description:

This issue ticket outlines a series of enhancements and bug fixes required for the Unitary DX System module. The goal is to ensure robust functionality, accurate calculations, and comprehensive testing for this module. The following tasks are identified as critical next steps:

#### Tasks:

1. **Complete `unitary_dx_curves.json`:**
   - The `unitary_dx_curves.json` file is currently pending completion. Now, the class can be loaded correctly and 'get_ref_values()' works. This task involves finalizing the JSON structure and ensuring it contains all necessary data for the Unitary DX system.

2. **Develop I/O Process in `calc_rated_eff` Function:**
   - Enhance the `calc_rated_eff` function to improve its input/output processing capabilities. This development should focus on streamlining data handling and ensuring compatibility with various data formats.

3. **Correct `calc_eff_ect` Function Based on a Given Model:**
   - Address existing issues in the `calc_eff_ect` function. This task requires adjusting the function to align with a specified model, ensuring accuracy in efficiency calculations at different entering coil temperatures (ECT).

4. **Resolve Bugs in `get_ref_cond_flow_rate` Function:**
   - Pending bug fixes in the `get_ref_cond_flow_rate` function (originally identified in `chiller.py`) need to be addressed. This involves debugging and correcting the function to ensure it accurately retrieves reference condition flow rates.

5. **Create and Implement Test Cases:**
   - Develop comprehensive test cases for the Unitary DX system module. This includes creating scenarios that cover a wide range of use cases and conditions. Implement these tests to validate the functionality and reliability of the module.

#### Expected Outcomes:

- A fully functional and reliable Unitary DX system module in the software.
- Enhanced accuracy and efficiency in the system's performance calculations.
- A robust set of test cases ensuring the module's resilience against various scenarios and data inputs.

**Comment by lymereJ** [comment]
> 2. **Develop I/O Process in `calc_rated_eff` Function:**
>    
>    * Enhance the `calc_rated_eff` function to improve its input/output processing capabilities. This development should focus on streamlining data handling and ensuring compatibility with various data formats.

As discussed, this could be done for both chillers and DX unitary equipment.


> 3. **Correct `calc_eff_ect` Function Based on a Given Model:**
>    
>    * Address existing issues in the `calc_eff_ect` function. This task requires adjusting the function to align with a specified model, ensuring accuracy in efficiency calculations at different entering coil temperatures (ECT).

This is a chiller-specific function, I don't think that we'll need it for DX unitary equipment.

> 4. **Resolve Bugs in `get_ref_cond_flow_rate` Function:**
>  
>    * Pending bug fixes in the `get_ref_cond_flow_rate` function (originally identified in `chiller.py`) need to be addressed. This involves debugging and correcting the function to ensure it accurately retrieves reference condition flow rates.

This is already in #81.

**Comment by wanhanlong1130** [comment]
> > > 2. **Develop I/O Process in `calc_rated_eff` Function:**
> > >    
> > >    * Enhance the `calc_rated_eff` function to improve its input/output processing capabilities. This development should focus on streamlining data handling and ensuring compatibility with various data formats.
> > 
> > As discussed, this could be done for both chillers and DX unitary equipment.
> 
> Yes, I wrote it here as a pending task.
> > > 3. **Correct `calc_eff_ect` Function Based on a Given Model:**
> > >    
> > >    * Address existing issues in the `calc_eff_ect` function. This task requires adjusting the function to align with a specified model, ensuring accuracy in efficiency calculations at different entering coil temperatures (ECT).
> > 
> > This is a chiller-specific function, I don't think that we'll need it for DX unitary equipment.
> 
>But do we need some functions to calculate efficiency based on some inputs for DX system?
> > > 4. **Resolve Bugs in `get_ref_cond_flow_rate` Function:**
> > >    
> > >    * Pending bug fixes in the `get_ref_cond_flow_rate` function (originally identified in `chiller.py`) need to be addressed. This involves debugging and correcting the function to ensure it accurately retrieves reference condition flow rates.
> > 
> > This is already in #81.
>
>Yes, but do we need a 'get_ref_cond_flow_rate' function for DX system? For air condenser, I don't think so; but for water condener?

**Comment by lymereJ** [comment]
> > > > 2. **Develop I/O Process in `calc_rated_eff` Function:**
> > > >    
> > > >    * Enhance the `calc_rated_eff` function to improve its input/output processing capabilities. This development should focus on streamlining data handling and ensuring compatibility with various data formats.
> > > 
> > > 
> > > As discussed, this could be done for both chillers and DX unitary equipment.
> > 
> > 
> > Yes, I wrote it here as a pending task.

Let's open issues for each individual tasks so they can be referenced in pull requests and commits.

> > > > 3. **Correct `calc_eff_ect` Function Based on a Given Model:**
> > > >    
> > > >    * Address existing issues in the `calc_eff_ect` function. This task requires adjusting the function to align with a specified model, ensuring accuracy in efficiency calculations at different entering coil temperatures (ECT).
> > > 
> > > 
> > > This is a chiller-specific function, I don't think that we'll need it for DX unitary equipment.
> > 
> > 
> > But do we need some functions to calculate efficiency based on some inputs for DX system?

We do, but it would be done through `calc_rated_eff`, `calc_rated_eff` is specific to chillers.

> > > > 4. **Resolve Bugs in `get_ref_cond_flow_rate` Function:**
> > > >    
> > > >    * Pending bug fixes in the `get_ref_cond_flow_rate` function (originally identified in `chiller.py`) need to be addressed. This involves debugging and correcting the function to ensure it accurately retrieves reference condition flow rates.
> > > 
> > > 
> > > This is already in #81.
> > 
> > 
> > Yes, but do we need a 'get_ref_cond_flow_rate' function for DX system? For air condenser, I don't think so; but for water condener?

Probably not.

**Comment by wanhanlong1130** [comment]
Open two new issues, and closed this one.
