### ISSUE TITLE
Unitary DX Issues

### ISSUE THREAD

**Issue by lymereJ** [pnnl/copper#96]
- [ ] `compressor_speed` is not assigned, see [here](https://github.com/pnnl/copper/blob/fe18acd7708deb10cd13c79cc27ee32efb8eb57e/copper/unitarydirectexpansion.py#L28C9-L28C25)
- [ ] there's not units for the capacity, users might want to specify the capacity using different units, just like for chillers

**Comment by wanhanlong1130** [comment]
Update both.
